server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://svc.sel4.cloudtype.app:32398/powerful-maria
    username: powerfulh
    password: 123153

  profiles:
    active: local

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

logging:
  pattern:
    console: "%-5level %logger{36} - %msg [%thread]%n"
#    console: "%d{MMdd HH:mm:ss} %-5level %logger{36} - %msg [%thread]%n"