server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADBDOMAIN}
    username: powerfulh
    password: ${MARIADBPASSWORD}

#  profiles:
#    active: local

mybatis:
  mapper-locations: classpath:mapper/**/*.xml