spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADBDOMAIN}
    username: powerfulh
    password: ${MARIADBPASSWORD}

#  profiles:
#    active: local

logging:
  pattern:
    console: "%-5level %logger{36} - %msg [%thread]%n"